name: ml_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.22.0
  - pandas=1.4.0
  - matplotlib=3.5.1
  - scipy=1.8.0
  - seaborn=0.11.2
  - scikit-learn=1.0.2
  - tensorflow=2.9.0
  - pytorch=1.11.0
  - keras=2.8.0
  - fastai=2.5.3
  - sympy=1.10.1
  - transformers=4.15.0
  - nltk=3.6.5
  - spacy=3.2.1
  - gensim=4.1.2
  - opencv=4.5.5
  - plotly=5.5.0
  - bokeh=2.4.2
  - dash=2.2.3
  - statsmodels=0.13.2
  - tqdm=4.62.3
  - scrapy=2.5.1
  - beautifulsoup4=4.10.0
  - pillow=9.0.1
  - xgboost=1.5.1
  - lightgbm=3.3.2
  - catboost=1.0.3
  - pip
  - pip:
      - some-pip-package==1.2.3  # Example for any pip-only package
 
